package com.example.blood_bud.data.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Data class representing a blood stock item in the inventory.
 *
 * @property id Unique identifier for the stock item (auto-generated by Firestore)
 * @property bloodType The blood type (e.g., "A+", "B-", "O+")
 * @property units The number of units available for this blood type
 * @property lastUpdated Timestamp when this stock item was last updated
 */
@Parcelize
data class StockItem(
    val id: String = "",
    val bloodType: String = "",
    var units: Int = 0,
    val lastUpdated: Long = System.currentTimeMillis()
) : Parcelable {
    // Required empty constructor for Firestore
    constructor() : this("", "", 0, 0)
    
    companion object {
        /**
         * List of all possible blood types
         */
        val BLOOD_TYPES = listOf(
            "A+", "A-", 
            "B+", "B-", 
            "AB+", "AB-", 
            "O+", "O-"
        )
        
        /**
         * Creates a new StockItem with the given blood type and units
         */
        fun create(bloodType: String, units: Int = 0): StockItem {
            return StockItem(
                bloodType = bloodType,
                units = units.coerceAtLeast(0), // Ensure units are not negative
                lastUpdated = System.currentTimeMillis()
            )
        }
    }
    
    /**
     * Validates if the stock item has valid data
     */
    fun isValid(): Boolean {
        return bloodType.isNotBlank() && units >= 0
    }
    
    /**
     * Returns a copy of this StockItem with updated units
     */
    fun withUpdatedUnits(newUnits: Int): StockItem {
        return copy(units = newUnits.coerceAtLeast(0), lastUpdated = System.currentTimeMillis())
    }
    
    /**
     * Returns a copy of this StockItem with the specified units added
     */
    fun withAdditionalUnits(additionalUnits: Int): StockItem {
        return copy(units = (units + additionalUnits).coerceAtLeast(0), lastUpdated = System.currentTimeMillis())
    }
}
